#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Saltmine Overview
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/saltmine/saltmine-overview.org
  :Created:   2017-05-26T17:36@Prek Leap (11.642600N-104.919210W)
  :ID:        82d92c66-ce35-4cfc-94cd-c48cd6579b53
  :VER:       549067083.896693001
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XRC7-4777
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


Saltmine is a software stack designed to provide an ITC
infrastructure for a scalable distributed civilization.  Up
until now it has always been seen as a collection of
software applications.  But we're now stepping back and
realizing it needs a broader vision.

So, like our reimagined Bento Box, Saltmine is no longer
simply code, but a set of specifications, data structures
and requirements for delivering a broad set of defined
functionality.  We will likely have a set of uniform APIs,
but other than that it won't matter what actually software
is used to get the job done.  It could be something fast and
close to the the metal in C or Rust, or fantastically rich
code written in Lisp.  It could be written in javascript
or perl or whatever.  It can be off the shelf applications
that are used to provide different parts of the stack -- it
doesn't matter so long as it get's the job done.




