#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Saltmine Overview
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/saltmine/saltmine-overview.org
  :Created:   2017-05-26T17:36@Prek Leap (11.642600N-104.919210W)
  :ID:        82d92c66-ce35-4cfc-94cd-c48cd6579b53
  :VER:       549067083.896693001
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XRC7-4777
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


Saltmine is a software stack designed to provide an ITC
infrastructure for a scalable distributed civilization.  Up
until now it has always been seen as a collection of
software applications.  But we're now stepping back and
realizing it needs a broader vision.

So, like our reimagined Bento Box, Saltmine is no longer
simply code, but a set of specifications, data structures
and requirements for delivering a broad set of defined
functionality.  We will likely have a set of uniform APIs,
but other than that it won't matter what actual software
is used to get the job done.  It could be something fast and
close to the the metal in C or Rust, or fantastically rich
code written in Lisp.  It could be written in javascript
or perl or whatever.  It can be off the shelf applications
that are used to provide different parts of the stack -- it
doesn't matter so long as it get's the job done.

---

d9d is the network built out of nodes using saltmine and
bento.  

d9d spins up containers as close to you as possible, that
then allow you to pick up any device and use it as if it
were your own device.

what I'm still unsure about is if we can use IPFS -- but
ipfs is file storage that distributes files across a
network.

saltmine is processing, storage, and messaging 

but it's also about breaking up collections of information
into different overlapping pieces, sometimes scattering
them, sometimes consolidating them.

could we treat containers just like files in IPFS, but each
node that stores something can then fire it up as a
container....

  - knows what you are
  - knows where you are
  - knows who you are
  - knows what role you are in

  - collects surrounding context
    - what you are doing
    - environment, light, temp, humidity, air pressure,
      gravity, noise.
    - identifies who is around you
    - searches for information related to all of these things


  - looks for devices near you to run on
  - looks for displays and interface devices near you

  - keeps track of how many copies of everything there are
  - 

---

#+begin_comment
Still can't seem to get my groove back....
#+end_comment


if we think of everything in saltmine as if it were an ERP
process -- everything in the process of becoming something
else.....  what does that even mean? 

but at the same time everything is also becomes part of the
map, which is a DAG but the graph as map is just how we pull
together context that triggers and informs processes, and a
map of a process is a thread running through the map.

maps represent holonic structures, and a process is just a
segment of a causal chain that propagates through the map,
changing it like light propagating across a light cone.

rule sets determine how we filter and see maps in different
ways, and find things, nodes, patterns etc.  but they also
govern how processes play out -- a rule set defines intent,
or at the least reflects past experience.
