#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Laurea
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/saltmine/saltmine-laurea.org
:Created:   2017-11-14T17:49@Prek Leap (11.642600N-104.919210W)
:ID:        e65a6b41-c92b-4692-93df-459c69a98688
:VER:       563928663.293416097
:GEO:       48P-491193-1287029-15
:BXID:      proj:MBJ2-2706
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Education

Learning is a kind of research and vice versa.  In both cases the goal
is to aquire and integrate new knowledge.  So academic and scientific
inquiry is functionally the same thing, but different methods are
employed.  Learning can be diadactic instruction to learn what has
already been discovered by others, or scientific which poses
propsitions and questions then endevours to collect information that
is then tested to prove or disprove the validity of the propasition or
the answer to the question.

This is why so much research is conducted at universities. The whole
purpose of a university is to help people to master what is known, and
to give them the intellectual tools needed to conduct research to
further what is known.

* Liberal Arts & Sciences

  - Trivium :: 3-4 years (typically begun age 11)
    - grammer   :: symbols
    - logic     :: thinking
    - rhetoric  :: communication

  - Quadrivium :: 3-4 years

    theory of information as matter, energy, space/time

    - Cosmos      :: theory of context
      - mimesis   :: maps/models
      - rhizomata :: structures
      - systema   :: systems 
      - transacta :: processes

    - Techne : application of context

      Techne teach broad core skills and knowledge that all advanced
      study is based on.  A given Techne is the closest thing to a
      traditional school subject.  But they are not the same.  All
      eight /subjects/ are taught in a cross disciplinary way, so that
      when you are learning about classical newtonian mechanics in
      /physics/, you are learning about Issac Newton in /history/ and
      how to caluculate and compute it in /math/.  And taken together,
      all techne are understood to belong to the larger context
      learned in /Cosmos/.  The techne add breadth and depth to the
      /cosmos/.

      - Math
      - Computation
      - Physics
      - Chemistry
      - Biology
      - History
      - Literature
      - Philosophy :: not the same as the history of philosophy

      Though the completion of the Trivium and Quadrivium is usually
      complete by the time a student is 18 years old, it is the
      equivilant of a bachelor's degree in liberal arts which is a
      foundation for all other study.  To modern ears this sounds
      strange and unrealistic.  But this is only because modern
      educational systems are not designed to send people to
      university, but to provide minimal literate and arithmatic
      skills that were required in factories and entry level offices
      in large companies.  These are mass skills required for an
      mechanical, industrial civilization based on the assembly line.
      The traditional liberal arts prepares the mind for higher level
      studies, so students who have completed the Trivium are far
      better prepared to undertake undergraduate level studies instead
      of the watered down secondary school studies that have to be
      repeated in more depth in the first years of university.

      Those who choose to continue in advanced studies will then take
      the Laurea.  Those who do not can then take Practicums for a
      given profession.  A person who wants to become a baker or
      woodworker could then take practicums in those subjects and be
      done with it.  There is no reason for a baker not to take the
      Laurea as well.  In fact, for a baker or woodworker to be given
      the rank of /master/ by their guild, they will have had to
      complete the Laurea.

  - Laurea : 3-6 years

    The Laurea teaches how to integrate everything learned in the
    Trivium and Quadrivium into a larger and deeper understanding of
    the world and provides practical research, learning and analytical
    skills in applying that knowledge to do or learn anything in life.

    One may take many different practicums over a lifetime but few
    people will do more than one Laurea.  

    The Laurea is a saturation job to learn as much as can be learned
    about a very specific subject and to present what is learned in a
    scholarly work.  This requires that a student undertakes in depth
    study in different aspects relating to the subject they are
    saturating themselves in.  This means that they may have to take
    any number of practicums to learn to read or speak one or more
    foreign languages, undertake studies in specialized fields of
    mathematics, history and philosophical inquiry.

  - Laurea Magister :: a second /cycle/ degree program undertaken
    after the Laurea in fields such as Engineering, Medicine, Law,
    Architecture etc.

  - Laurea Practicum :: is a degree program for training in a
    specialized field after one has completed a Laurea, and Laurea
    Magister.

  - Practicum :: teaches practical specialized skills and acts as a
    professional qualification, the practicum is a course of study to
    aquire skills of a practical nature in the workplace.  Practicums
    are relatively short (six months to 2 years), and are meant to be
    done along side the Quadrivium and Laurea.  This allows people to
    apply knowledge form the quadrivium and laurea to the real world
    and earn a living doing so.  Most Practicums are utilitarian in
    nature, but they also include technical, theory and fine arts.  So
    a Practicum can be anything from teaching primary school, welding,
    nursing, woodworking, dance, music (learning to play an
    instrument, music theory is studied in a Laurea), programing,
    design etc.

    It's important to understand that a Pacticum is more than a
    vocational training or certificate training, it builds on the
    skills aquired from the Trivium, Quadrivium and Laurea.

    A Laurea is not enough to qualify to practice a given profession,
    but a Laurea gives the skills needed to apply the skills learned
    in a Practicum to do so.  It is common to take two or more
    Practicums during and after completing a Laurea to qualify in a
    field.

    As professions evolve over time it's expected for all practicing
    professionals to continue to take various practicums to stay
    current in a field.

  - Master/Magister :: 
    The highest title that can be bestowed.  A Laurea is the
    equivilent to a PhD which means a person is qualified to practice, 
    but a Master has practiced his art and science long enough to
    produce an original work that furthers knowledge in a significant 
    way.  This doesn't mean a master has to win a nobel prize, but it
    does set them apart from a PhD, as a person who is experienced and
    practiced to the point where they can teach others at the PhD
    level.  The only thing needed to become a Master is for the Guild
    they belong to, to declare that a work or works that a PhD has 
    completed qualifies as a Master work.

    I'm not sure that this is something that you really formally apply 
    for, or if the work done by PhD's in a Guild are monitored by the
    Guild and when the Guild deems work worthy of a Master, the title 
    is given.

** Examples

If someone wants to become a representative for a polity or bioregion
they need to have completed a Laurea and a Laurea Practicum in
governance, which includes a thorough grounding in ethics, diplomacy,
political history, management, leadership, as well as legal, economic
and statistical theory.  They will already have a solid foundation in
logic and rhetoric, but these areas will be reinforced by the study
program which is, afterall, training people to think critically,
engage with and negotiate (and compromise) with others and communicate
effectively with those they represent.

All representitives and diplomats must belong to the Ethics Guild as
well as a Guild of Representives or Diplomats in good standing.  If a
representitive is found guilty of unethical behavior by the Guild they
can be expelled from the Guild which would bar that person from
holding office.  So this would work something like the Bar or Medical
Association that grants licences for practicing.  They also have an
obligation to remove those who engage in unethical behavior.

BTW all office holders are required to be open to a higher level of
personal and financial transparency well as be monitored while in
office and for an extended period afterwards to ensure that they have
not used the office for unreasonable personal gain.


* Guilds

The term /guild/ has more than a little baggage.  Historically, guilds
have acted as unions, provide education in their fields, and ensured
levels of quality.  They have also at different times become
entrenched monopolies that control markets and exclude others from
entering markets.

Today Guilds are alive and well though they often call themselves
things like like the Bar or Medical Association.  But in both cases,
members are held accountable to their guild to practice their art with 
professional competence of the state of the art, and to behave in an
ethical manner or face expulsion and loose their ability to pratice.

We see a Guild as being a providing checks and balances between the
educational and professional realms.  Guilds are barred from political
or lobbying activities both in educational, state or corporate
environments.  A Guild is the caretaker of the knowledge that is
required for Guild members in their field.  They are responsible for
furthering the knowledge and art of their field. And they are
responsible for maintaining the quality of the work done in a field
and to bestow credentials and licences in their given field.

Unlike historical Guilds, different guilds overlap each other, so that
they maintain cross-disciplinary links with other guilds and ensure
that specialization does not come at come at the expense of
compartmentalization.  This is a very difficult thing to do as both an
individual and as an organization because it means they they have to
share turf and cooperate and share more than compete.  We need to
structure guilds so that the more they cooperate and share the more
successful and influential they will become.  For this reason, many
people will belong to and work with a spectrum of guilds and in this
way, guilds will provide checks and balances on each other.

A guild may not only help fund and promote research, but undertake it
as well.  A guild may maintain and develop educational programs and
sponsor teachers in educational instutions.  A guild may provide
testing, quality control and certification of commercial products.  In
the case of agricultural products this overlaps with health and safety
inspection and certifican. 

A guild must be distributed, so that any one guild can not become a
monolithic organization.  This will make it possible to police guild
chapters who stray or go rogue.

* Shops

A shop is a place where work is done that is part of the network.
Shops can be commerical or non-commercial.  They can produce physical
goods or ideas.

You can't separate learning and research from work, the three are
different aspects of the same thing.

Guilds overlap with shops since members of shops are guild members,
and guilds train people who work in shops, guilds help keep shops
honest, but shops make guilds possible.

* Polity

There are nations, states and nation-states that combine the two.

A state is first and foremost a physical territory with a legible
border and population.

States have infrastructure which is divided into two parts.  The first
is physical things like roads, electrical grids, water and sewage
systems, communication and railway networks, airports etc.  The second
are made up of services which are provided by institutions such as
police forces, armed forces, legal systems, banks, legislature and 
executive bodies, courts, libraries, hospitals, schools etc.

States are all about organizing people and physical things to produce
a surplus of wealth (in the form of goods, food etc) that can then be
used to pay for a ruling class, and specializations which are not
directly related to day to day survival.  The surplus that the state
collects to pay for services and the ruling class is a tax.  No taxes
and there is no state.  But does that mean that if there are no taxes
there are no services?  Some believe that all services can be satisfied
by an open competitive commercial market.  This is clearly not the
case.

There are all sorts of services provided by states which are terrible
at turning a profit.  Not all public needs can be met by markets.  By
the same token states are terrible at providing many services as well.
The problem is that states don't scale very well.  Humans seem to do
well in communities up to about 5,000 people in size and after that
hierarchical organization begin to errode the the quality of life,
liberty and freedom of many individuals and create wealth imbalances.

Is is possible to build an advanced technological civilization without
states?

To do so we need to:

  - keep local polities at or under 5,000 people.
  - provide physical infrastructure -- maintained roads, electricity,
    water, fuel, communications and waste management.
  - provide institutional services such as libraries, education, legal,
    enforcement, and commerce systems.
  - interconnect local polities with neighboring polities and ensure
    that any polity will be be able to interact with any other polity
    according to the same rules.
  - ensure freedom of expression, speech, and movement.

The problem is that the planet is not homogenous -- different places
have access to different kinds of resources.  Ensuring that this does
not result in power imbalances that screw things up is difficult.

Blockchain technology provides a mechanism for trustless networks to
take over many institutional services where transactions are taking
place between parties who are more than a single hop from each other.

We can automate large parts of supply and value chains -- if everyone
is basically using the same network and playing by the same rules a
lot of middlemen charging rents are eliminated.

No one can do everything alone, that's the fatal flaw that preppers
and homesteaders don't get until it's too late.  Its impractical for
most people to generate all of their own electricity, some or even
maybe most of it yes, but all, but for most places it's neither easy
or economical.

So let's look at structures larger than a 5K person polity.  Polities
can behave as parts of larger urban centers -- so a large city is just
a bunch of polities that are packed tightly together.

We can also group polities into bioregions -- that helps because they
will share the same climate, ecosystem, culture, language etc so it
won't be too difficult to establish an equitible egalitarian systems
for polities to interact and cooperate with each other.

There will be some very significant disparities between different
bioregions though in terms of population, agricultural production,
heating and cooling, rainfall etc.  I do think that on the whole, we
can get to the point where almost all bioregions can juggle things to
provide basic physical infrastructure and a majority of food produced
within the bioregion.  Shortfalls in one thing or another can be made
up by increasing production of what is easy to produce a surplus of
and trade with other bioregions.  This is classical economic theory.

But it's important that no polity or bioregion becomes too specialized
-- if every polity can produce 40% of their own core needs themselves
with the bioregion providing another 40%, the bioregion only needs to
trade for the last 20%.

That will take a huge amount of pressure off any one polity or
bioregion and reduce competition and wealth imbalances?  I'm not sure
that follows but it's something to think about.

There are some things that are still missing.  Heavy industry that
doesn't work well at small scales, and very large scale products that
can't be done by small communities.  Building a 747, or a container
ship, spaceships or a suspension bridge are things that require large
investment of capital, manpower and resources.

There are scientific and research projects that requires huge
resources -- how could we finance something like the Large Hadron
Collider?

My feeling is that these things could be financed by the network
itself -- the network will be taking a percentage of transactions to
finance itself, so it makes sense for some of that money to be used
for large scale projects.

The next problem is large scale coordination -- disaster relief, large
scale dislocation of populations, and working out what projects will
be done when and where.

We would need something like a world organization made up of
bioregions who could set priorities and coordinate projects, mediate
disputes between bioregions.  Again, since bioregions will be largely
self supporting, there won't be as much pressure for any one bioregion
to grab more than their share.  Funds can be set up for disaster
relief, and money pooled to provide large scale infrastructure loans
for things that would be difficult for a single bioregion to finance
themselves.

** Educational shops and universities as polities

Would it be possible for a politiy to actually be a university in it's
own right?  Large campuses are pretty much self-contained towns
already, and a large university in an urban environment is certaintly
a kind of neighborhood.  This would provide the university with the
political means to seek funding for research facilities and for large
projects.

An educational shop might focus on pre-school, or teaching the trivium
to children in a bioregion.
